# Conditionals: `if: github.ref == 'refs/heads/main'`
name: conditional-demo

on:
 push:
   branches: [main]
 # pull_request:
 #   branches: [main]
 # workflow_dispatch:

jobs:
  # when_main:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: runs when the branch is main
  #      if: github.ref == 'refs/heads/main'
  #      run: |
  #       echo "runs when the branch is main"
  #       # exit 1

  #    - name: only runs when the previous step failed
  #      if: failure()
  #      run: echo "Previous step failed....."

  on-push:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: only run on push events
        run: echo "Only run on push events"
        # continue-on-error: true
   
     
