name: Ignore Docs Workflow

on:
  workflow_dispatch: 
  # push:
  #   branches:
  #     - main
  #     - 'release/*'
  #   paths-ignore:
  #     - '*.md'
  #     - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print event
        run: echo "${{ toJson(github.event) }}"

      - name: Run workflow task
        run: echo "Workflow run because change was not docs-only"
