name: pr check workflow

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  pr-check:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: print branch name
        run: |
          echo "PR check running for branch: ${{ github.head_ref }}"