name: reusable build workflow

on:
  workflow_call:
    inputs:
      app_name:
        description: "App Name"
        required: true
        type: string
      environment:
        description: "Deploy Environment"
        required: true
        default: "staging"
        type: string
    secrets:
      docker_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print build info
        run: |
          echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

      - name: verify docker token status
        run: |
          if [ -n "${{ secrets.docker_token }}" ]; then
            echo "Docker token is set: true"
          else
            echo "Docker token is set: false"
          fi
